"""
OCServ：在 protocol=ocserv 时自动安装 ocserv + radcli、写入 RADIUS 与 TLS 配置并启动服务。
参见 ocserv 文档：doc/README-radius.md（radcli 配置）。
"""
from __future__ import annotations

import logging
import os
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from common.config import (
    get_node_protocol,
    get_ocserv_domain,
    get_ocserv_port,
    get_ocserv_radius_acct_port,
    get_ocserv_radius_auth_port,
    get_ocserv_radius_host,
    get_ocserv_radius_secret,
    get_ocserv_tls_pem_from_env,
    get_node_wg_dns,
    get_vpn_ip_cidrs,
    skip_system_commands,
)

logger = logging.getLogger(__name__)

OCSERV_CONF = "/etc/ocserv/ocserv.conf"
RADCLI_CONF = "/etc/radcli/radiusclient.conf"
RADCLI_SERVERS = "/etc/radcli/servers"
TLS_DIR = "/etc/ocserv/ssl"
TLS_CERT = f"{TLS_DIR}/server.crt"
TLS_KEY = f"{TLS_DIR}/server.key"


def reload_ocserv() -> None:
    if skip_system_commands():
        return
    subprocess.run(
        ["systemctl", "reload", "ocserv"],
        capture_output=True,
        check=False,
    )


def _first_ipv4_cidr() -> str:
    raw = get_vpn_ip_cidrs()
    for part in raw.split(","):
        p = part.strip()
        if p and "/" in p:
            return p
    return "10.66.0.0/24"


def _remove_stale_configs_before_first_apt() -> None:
    """若先前 apt 失败但已写入本脚本配置，dpkg 会交互式询问；在首次安装 ocserv 前删掉。"""
    if shutil.which("ocserv"):
        return
    try:
        p = OCSERV_CONF
        if os.path.isfile(p):
            with open(p, encoding="utf-8") as f:
                head = f.read(120)
            if "Generated by vpn-node-agent" in head:
                os.remove(p)
                logger.info("ocserv: removed stale %s before apt", p)
    except OSError as exc:
        logger.warning("ocserv: could not remove stale config: %s", exc)
    # 错包名导致 ocserv 未装时可能已有手写 radiusclient.conf，与 dpkg 冲突（勿删整目录 / dictionary）
    try:
        rc = "/etc/radcli/radiusclient.conf"
        if os.path.isfile(rc):
            with open(rc, encoding="utf-8") as f:
                t = f.read()
            if "servers /etc/radcli/servers" in t and "authserver" in t:
                os.remove(rc)
                logger.info("ocserv: removed stale %s before apt", rc)
        sv = "/etc/radcli/servers"
        if os.path.isfile(sv):
            os.remove(sv)
            logger.info("ocserv: removed stale %s before apt", sv)
    except OSError:
        pass


def _install_debian_packages() -> None:
    if not os.path.isfile("/etc/debian_version"):
        logger.warning("ocserv: 仅 Debian/Ubuntu 下自动 apt 安装；请手动安装 ocserv（及依赖 libradcli）")
        return
    if shutil.which("ocserv"):
        return
    _remove_stale_configs_before_first_apt()
    # Ubuntu/Debian：包名是 ocserv（依赖 libradcli4），不存在名为 radcli 的包
    env = os.environ.copy()
    env["DEBIAN_FRONTEND"] = "noninteractive"
    logger.info("ocserv: installing package ocserv (pulls libradcli)")
    subprocess.run(["apt-get", "update", "-qq"], env=env, check=False)
    r = subprocess.run(
        [
            "apt-get",
            "install",
            "-y",
            "-qq",
            "-o",
            "Dpkg::Options::=--force-confnew",
            "ocserv",
        ],
        env=env,
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        logger.error("ocserv: apt install failed: %s", r.stderr or r.stdout)
        raise RuntimeError("ocserv: apt install ocserv failed; check network and apt sources")


def _write_tls_files() -> None:
    cert, key = get_ocserv_tls_pem_from_env()
    if not cert or not key:
        raise RuntimeError("NODE_OCSERV_TLS_CERT_B64 / NODE_OCSERV_TLS_KEY_B64 missing or invalid")
    os.makedirs(TLS_DIR, mode=0o755, exist_ok=True)
    with open(TLS_CERT, "w", encoding="utf-8") as f:
        f.write(cert)
    with open(TLS_KEY, "w", encoding="utf-8") as f:
        f.write(key)
    os.chmod(TLS_CERT, 0o644)
    os.chmod(TLS_KEY, 0o600)


def _ensure_radcli_dictionary() -> None:
    """若 /etc/radcli/dictionary 缺失（例如曾误删 /etc/radcli），用 apt 补回 conffile。"""
    if os.path.isfile("/etc/radcli/dictionary"):
        return
    if not os.path.isfile("/etc/debian_version"):
        return
    logger.warning("ocserv: restoring missing /etc/radcli/dictionary via apt reinstall libradcli4")
    env = os.environ.copy()
    env["DEBIAN_FRONTEND"] = "noninteractive"
    subprocess.run(
        [
            "apt-get",
            "install",
            "--reinstall",
            "-y",
            "-o",
            "DPkg::Options::=--force-confmiss",
            "libradcli4",
        ],
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )


def _write_radcli() -> None:
    host = get_ocserv_radius_host()
    secret = get_ocserv_radius_secret()
    if not host or not secret:
        raise RuntimeError("NODE_OCSERV_RADIUS_HOST or RADIUS secret missing")
    auth = get_ocserv_radius_auth_port()
    acct = get_ocserv_radius_acct_port()
    os.makedirs(os.path.dirname(RADCLI_CONF), mode=0o755, exist_ok=True)
    # radcli：authserver / acctserver 与 servers 文件（见 ocserv README-radius）
    lines = [
        "dictionary /etc/radcli/dictionary",
        # radcli：须设置 timeout / retries，否则 rc_test_config 失败
        "radius_timeout 5",
        "radius_retries 3",
        f"authserver {host}:{auth}",
        f"acctserver {host}:{acct}",
        f"servers {RADCLI_SERVERS}",
        "",
    ]
    with open(RADCLI_CONF, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    os.chmod(RADCLI_CONF, 0o644)
    # servers：hostname<TAB>secret<TAB>timeout
    srv_line = f"{host}\t{secret}\t5\n"
    with open(RADCLI_SERVERS, "w", encoding="utf-8") as f:
        f.write(srv_line)
    os.chmod(RADCLI_SERVERS, 0o600)


def _write_ocserv_conf() -> None:
    port = get_ocserv_port()
    domain = get_ocserv_domain() or "vpn.local"
    dns = get_node_wg_dns()
    ipv4 = _first_ipv4_cidr()
    body = f"""# Generated by vpn-node-agent — do not edit by hand

tcp-port = {port}
udp-port = {port}
run-as-user = nobody
run-as-group = nogroup
socket-file = /run/ocserv/ocserv.sock
pid-file = /run/ocserv/ocserv.pid
device = vpns0
ipv4-network = {ipv4}
route = default
dns = {dns}
default-domain = {domain}
server-cert = {TLS_CERT}
server-key = {TLS_KEY}
auth = "radius[config={RADCLI_CONF},groupconfig=true]"
acct = "radius[config={RADCLI_CONF}]"
stats-report-time = 300
"""
    os.makedirs(os.path.dirname(OCSERV_CONF), mode=0o755, exist_ok=True)
    with open(OCSERV_CONF, "w", encoding="utf-8") as f:
        f.write(body)
    os.chmod(OCSERV_CONF, 0o644)


def _ensure_run_ocserv_dir() -> None:
    """ocserv sec-mod 需在 /run/ocserv 下创建 unix socket；若目录不存在会 bind 失败。"""
    os.makedirs("/run/ocserv", mode=0o755, exist_ok=True)


def _write_ocserv_systemd_dropin() -> None:
    """保证重启后 /run/ocserv 仍存在（tmpfs 上由 systemd 创建）。"""
    drop = "/etc/systemd/system/ocserv.service.d"
    os.makedirs(drop, mode=0o755, exist_ok=True)
    p = f"{drop}/vpn-agent-runtime.conf"
    with open(p, "w", encoding="utf-8") as f:
        f.write("[Service]\nRuntimeDirectory=ocserv\n")
    os.chmod(p, 0o644)


def _systemd_enable_ocserv() -> None:
    _ensure_run_ocserv_dir()
    _write_ocserv_systemd_dropin()
    subprocess.run(["systemctl", "daemon-reload"], capture_output=True, check=False)
    subprocess.run(["systemctl", "enable", "ocserv"], capture_output=True, check=False)
    r = subprocess.run(
        ["systemctl", "restart", "ocserv"],
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        logger.error("ocserv: systemctl restart failed: %s", r.stderr or r.stdout)
        raise RuntimeError("ocserv: systemctl restart failed")
    logger.info("ocserv: service restarted")


def ensure_ocserv_deployed() -> None:
    if get_node_protocol() != "ocserv":
        return
    if skip_system_commands():
        logger.info("ocserv: SKIP_SYSTEM_COMMANDS=1, skip deploy")
        return
    try:
        _install_debian_packages()
        _ensure_radcli_dictionary()
        _write_tls_files()
        _write_radcli()
        _write_ocserv_conf()
        _systemd_enable_ocserv()
        logger.info("ocserv: deployed and active (protocol=ocserv)")
    except Exception as exc:
        logger.error("ocserv: deploy failed: %s", exc)
        raise
