"""
OCServ：在 protocol=ocserv 时自动安装 ocserv + radcli、写入 RADIUS 与 TLS 配置并启动服务。
参见 ocserv 文档：doc/README-radius.md（radcli 配置）。
"""
from __future__ import annotations

import logging
import os
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from common.config import (
    get_node_protocol,
    get_ocserv_domain,
    get_ocserv_port,
    get_ocserv_radius_acct_port,
    get_ocserv_radius_auth_port,
    get_ocserv_radius_host,
    get_ocserv_radius_secret,
    get_ocserv_tls_pem_from_env,
    get_node_wg_dns,
    get_vpn_ip_cidrs,
    skip_system_commands,
)

logger = logging.getLogger(__name__)

OCSERV_CONF = "/etc/ocserv/ocserv.conf"
RADCLI_CONF = "/etc/radcli/radiusclient.conf"
RADCLI_SERVERS = "/etc/radcli/servers"
TLS_DIR = "/etc/ocserv/ssl"
TLS_CERT = f"{TLS_DIR}/server.crt"
TLS_KEY = f"{TLS_DIR}/server.key"

def _write_file_if_changed(path: str, content: str, mode: int | None = None) -> bool:
    old = None
    try:
        with open(path, "r", encoding="utf-8") as f:
            old = f.read()
    except FileNotFoundError:
        old = None
    except OSError:
        old = None

    if old == content:
        return False
    os.makedirs(os.path.dirname(path), mode=0o755, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    if mode is not None:
        os.chmod(path, mode)
    return True


def reload_ocserv() -> bool:
    if skip_system_commands():
        return False
    p = subprocess.run(
        ["systemctl", "reload", "ocserv"],
        capture_output=True,
        check=False,
        text=True,
    )
    if p.returncode != 0:
        logger.warning("ocserv: reload failed: %s", p.stderr or p.stdout)
        return False
    return True


def _first_ipv4_cidr() -> str:
    raw = get_vpn_ip_cidrs()
    for part in raw.split(","):
        p = part.strip()
        if p and "/" in p:
            return p
    return "10.66.0.0/24"


def _remove_stale_configs_before_first_apt() -> None:
    """若先前 apt 失败但已写入本脚本配置，dpkg 会交互式询问；在首次安装 ocserv 前删掉。"""
    if shutil.which("ocserv"):
        return
    try:
        p = OCSERV_CONF
        if os.path.isfile(p):
            with open(p, encoding="utf-8") as f:
                head = f.read(120)
            if "Generated by vpn-node-agent" in head:
                os.remove(p)
                logger.info("ocserv: removed stale %s before apt", p)
    except OSError as exc:
        logger.warning("ocserv: could not remove stale config: %s", exc)
    # 错包名导致 ocserv 未装时可能已有手写 radiusclient.conf，与 dpkg 冲突（勿删整目录 / dictionary）
    try:
        rc = "/etc/radcli/radiusclient.conf"
        if os.path.isfile(rc):
            with open(rc, encoding="utf-8") as f:
                t = f.read()
            if "servers /etc/radcli/servers" in t and "authserver" in t:
                os.remove(rc)
                logger.info("ocserv: removed stale %s before apt", rc)
        sv = "/etc/radcli/servers"
        if os.path.isfile(sv):
            os.remove(sv)
            logger.info("ocserv: removed stale %s before apt", sv)
    except OSError:
        pass


def _install_debian_packages() -> None:
    if not os.path.isfile("/etc/debian_version"):
        logger.warning("ocserv: 仅 Debian/Ubuntu 下自动 apt 安装；请手动安装 ocserv（及依赖 libradcli）")
        return
    if shutil.which("ocserv"):
        return
    _remove_stale_configs_before_first_apt()
    # Ubuntu/Debian：包名是 ocserv（依赖 libradcli4），不存在名为 radcli 的包
    env = os.environ.copy()
    env["DEBIAN_FRONTEND"] = "noninteractive"
    logger.info("ocserv: installing package ocserv (pulls libradcli)")
    subprocess.run(["apt-get", "update", "-qq"], env=env, check=False)
    r = subprocess.run(
        [
            "apt-get",
            "install",
            "-y",
            "-qq",
            "-o",
            "Dpkg::Options::=--force-confnew",
            "ocserv",
        ],
        env=env,
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        logger.error("ocserv: apt install failed: %s", r.stderr or r.stdout)
        raise RuntimeError("ocserv: apt install ocserv failed; check network and apt sources")


def _write_tls_files() -> bool:
    cert, key = get_ocserv_tls_pem_from_env()
    if not cert or not key:
        raise RuntimeError("NODE_OCSERV_TLS_CERT_B64 / NODE_OCSERV_TLS_KEY_B64 missing or invalid")
    os.makedirs(TLS_DIR, mode=0o755, exist_ok=True)
    changed = False
    changed = _write_file_if_changed(TLS_CERT, cert, 0o644) or changed
    changed = _write_file_if_changed(TLS_KEY, key, 0o600) or changed
    return changed


def _ensure_radcli_dictionary() -> None:
    """若 /etc/radcli/dictionary 缺失（例如曾误删 /etc/radcli），用 apt 补回 conffile。"""
    if os.path.isfile("/etc/radcli/dictionary"):
        return
    if not os.path.isfile("/etc/debian_version"):
        return
    logger.warning("ocserv: restoring missing /etc/radcli/dictionary via apt reinstall libradcli4")
    env = os.environ.copy()
    env["DEBIAN_FRONTEND"] = "noninteractive"
    subprocess.run(
        [
            "apt-get",
            "install",
            "--reinstall",
            "-y",
            "-o",
            "DPkg::Options::=--force-confmiss",
            "libradcli4",
        ],
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )


def _write_radcli() -> bool:
    host = get_ocserv_radius_host()
    secret = get_ocserv_radius_secret()
    if not host or not secret:
        raise RuntimeError("NODE_OCSERV_RADIUS_HOST or RADIUS secret missing")
    auth = get_ocserv_radius_auth_port()
    acct = get_ocserv_radius_acct_port()
    # radcli：authserver / acctserver 与 servers 文件（见 ocserv README-radius）
    lines = [
        "dictionary /etc/radcli/dictionary",
        # radcli：须设置 timeout / retries，否则 rc_test_config 失败
        "radius_timeout 5",
        "radius_retries 3",
        f"authserver {host}:{auth}",
        f"acctserver {host}:{acct}",
        f"servers {RADCLI_SERVERS}",
        "",
    ]
    changed = _write_file_if_changed(RADCLI_CONF, "\n".join(lines), 0o644)
    # servers：hostname<TAB>secret<TAB>timeout
    srv_line = f"{host}\t{secret}\t5\n"
    changed = _write_file_if_changed(RADCLI_SERVERS, srv_line, 0o600) or changed
    return changed


def _write_ocserv_conf() -> bool:
    port = get_ocserv_port()
    domain = get_ocserv_domain() or "vpn.local"
    dns = get_node_wg_dns()
    ipv4 = _first_ipv4_cidr()
    body = f"""# Generated by vpn-node-agent — do not edit by hand

tcp-port = {port}
udp-port = {port}
run-as-user = nobody
run-as-group = nogroup
socket-file = /run/ocserv/ocserv.sock
pid-file = /run/ocserv/ocserv.pid
device = vpns0
ipv4-network = {ipv4}
route = default
dns = {dns}
default-domain = {domain}
server-cert = {TLS_CERT}
server-key = {TLS_KEY}
auth = "radius[config={RADCLI_CONF},groupconfig=true]"
acct = "radius[config={RADCLI_CONF}]"
use-occtl = true
occtl-socket-file = /var/run/occtl.socket
stats-report-time = 300
"""
    return _write_file_if_changed(OCSERV_CONF, body, 0o644)


def _ensure_run_ocserv_dir() -> None:
    """ocserv sec-mod 需在 /run/ocserv 下创建 unix socket；若目录不存在会 bind 失败。"""
    os.makedirs("/run/ocserv", mode=0o755, exist_ok=True)


def _write_ocserv_systemd_dropin() -> None:
    """保证重启后 /run/ocserv 仍存在（tmpfs 上由 systemd 创建）。"""
    drop = "/etc/systemd/system/ocserv.service.d"
    os.makedirs(drop, mode=0o755, exist_ok=True)
    p = f"{drop}/vpn-agent-runtime.conf"
    with open(p, "w", encoding="utf-8") as f:
        f.write("[Service]\nRuntimeDirectory=ocserv\n")
    os.chmod(p, 0o644)


def _systemd_enable_ocserv(changed_ocserv: bool, changed_radcli: bool, changed_tls: bool) -> None:
    _ensure_run_ocserv_dir()
    _write_ocserv_systemd_dropin()
    subprocess.run(["systemctl", "daemon-reload"], capture_output=True, check=False)
    subprocess.run(["systemctl", "enable", "ocserv"], capture_output=True, check=False)

    st = subprocess.run(["systemctl", "is-active", "ocserv"], capture_output=True, text=True)
    active = (st.stdout or "").strip() == "active"
    if not (changed_ocserv or changed_radcli or changed_tls) and active:
        return

    # 仅 radcli 变更时优先 reload（更平滑）；失败再 fallback restart
    if changed_radcli and not (changed_ocserv or changed_tls) and active:
        if reload_ocserv():
            logger.info("ocserv: reloaded (radcli changed)")
            return

    r = subprocess.run(
        ["systemctl", "restart", "ocserv"],
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        logger.error("ocserv: systemctl restart failed: %s", r.stderr or r.stdout)
        raise RuntimeError("ocserv: systemctl restart failed")
    logger.info("ocserv: service restarted")


def ensure_ocserv_deployed() -> None:
    if get_node_protocol() != "ocserv":
        return
    if skip_system_commands():
        logger.info("ocserv: SKIP_SYSTEM_COMMANDS=1, skip deploy")
        return
    try:
        _install_debian_packages()
        _ensure_radcli_dictionary()
        changed_tls = _write_tls_files()
        changed_radcli = _write_radcli()
        changed_ocserv = _write_ocserv_conf()
        _systemd_enable_ocserv(changed_ocserv, changed_radcli, changed_tls)
        logger.info("ocserv: deployed and active (protocol=ocserv)")
    except Exception as exc:
        logger.error("ocserv: deploy failed: %s", exc)
        raise
